CREATE DATABASE LAVADERO;

/*
DROP TABLE LAVADERO.AUTOS;
DROP TABLE LAVADERO.EMPLEADOS;
DROP TABLE LAVADERO.LAVADOS;
*/
CREATE TABLE LAVADERO.AUTOS (
    ID_AUTO INTEGER PRIMARY KEY AUTO_INCREMENT,
    MARCA VARCHAR(100),
    PATENTE VARCHAR(10),
    FECHA_CADUC DATE,
    ID_CLIENTE INTEGER ,
    FOREIGN KEY (ID_CLIENTE) REFERENCES LAVADERO.CLIENTE(ID_CLIENTE)
);

CREATE TABLE LAVADERO.CLIENTE (
    ID_CLIENTE INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
);

CREATE TABLE LAVADERO.EMPLEADOS(
    ID_EMPLEADO INTEGER primary key AUTO_INCREMENT,
    NOMBRE VARCHAR(200)
);

CREATE TABLE LAVADOS(
    ID_LAVADO INTEGER PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE VARCHAR(200)
);

CREATE TABLE EMPLEADO_LAVADOS(
    ID_EMPLEADO INTEGER,
    ID_LAVADO INTEGER
);

CREATE TABLE LAVADERO.INSUMO_INGRESOS(
    ID_INSUMO INTEGER,
    ID_INGRESO INTEGER,
    FOREIGN KEY (ID_INSUMO) REFERENCES LAVADERO.INSUMOS(ID_INSUMO),
    FOREIGN KEY (ID_INGRESO) REFERENCES LAVADERO.INGRESOS(ID_INGRESO)
);



